#Example
version: "2"

linters:
  default: none
  enable:
    - slogzaplint  
  settings:
    custom:
      slogzaplint:
        type: "module"
        description: This is an logging usage of a plugin linter.
        original-url: "https://github.com/LainIwakuras-father/slogzaplint"
        settings:
          enabled-rules:
            - english
          sensitive-patterns:
            - "api_key"

